name: Backup Automatico su Google Drive

on:
  push:
    branches: [ main ]

jobs:
  upload-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice dal repository
        uses: actions/checkout@v4

      - name: Genera timestamp per il nome del file
        id: timestamp
        run: echo "date=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Comprimi il sito in un archivio zip
        run: zip -r esp32-site-backup-${{ steps.timestamp.outputs.date }}.zip . -x "*.git*"

      - name: Carica il file zip su Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: 'esp32-site-backup-${{ steps.timestamp.outputs.date }}.zip'
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
