name: Backup Automatico su Google Drive

on:
  push:
    branches: [ main ]

jobs:
  upload-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice dal repository
        uses: actions/checkout@v4

      - name: Comprimi il sito in un archivio zip
        run: zip -r backup.zip . -x "*.git*"

      - name: Carica il file zip su Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: 'backup.zip'
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          parent_folder_id: ${{ secrets.GDRIVE_FOLDER_ID }}
